name: Treinamento GH Actions - Triggers

on:
 push:
  branches: 
   - master
 workflow_dispatch:

env:
 CAMINHO_PROJETO: ./SiteContagem/SiteContagem.csproj 
 CAMINHO_PUBLISH: app 
 NOME_ARTEFATO: APIContagem
 NOME_WEBAPP_AZURE: anp-admin

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: "Faz Checkout do Código Fonte"
      uses: actions/checkout@v2
    
    - name: "Instala o SDK do .NET Core 3.1 no Runner"
      uses: actions/setup-dotnet@v1
    
    - name: Build do Projeto
      run: dotnet publish ${{ env.CAMINHO_PROJETO }} -c Release -o ${{ env.CAMINHO_PUBLISH }}
      
    - name: Upload da Publicação como Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ${{ env.NOME_ARTEFATO }}
        path: ${{ env.CAMINHO_PUBLISH }}     

 deploy-dev:
   if: github.ref == 'refs/heads/developer'
   runs-on: ubuntu-latest
   needs: [build]
   steps:
    - name: Task 1 Exemplo
      if: success()
      run: echo 'Task 1 Exemplo '                    
 
 deploy-preprod:
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: [build]
   environment: 
    name: Dev
    url: https://anp-admin-preprod.azurewebsites.net
   steps:
    - name: Download do Artefato Gerado pelo Job de Build
      uses: actions/download-artifact@v2.0.8
      with:
        name: ${{ env.NOME_ARTEFATO }}
        path: ${{ env.CAMINHO_PUBLISH }}
      
    - name: Login no Azure
      uses: Azure/login@v1.1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deployment no Azure App Service
      uses: Azure/webapps-deploy@v2
      with:
       slot-name: preprod
       app-name: ${{ env.NOME_WEBAPP_AZURE }}
       package: ${{ env.CAMINHO_PUBLISH }}

 deploy-prod:
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   needs: [deploy-preprod]
   environment: 
    name: Prod
    url: https://anp-admin.azurewebsites.net   
   steps:
    - name: Download do Artefato Gerado pelo Job de Build
      uses: actions/download-artifact@v2.0.8
      with:
        name: ${{ env.NOME_ARTEFATO }}
        path: ${{ env.CAMINHO_PUBLISH }}
      
    - name: Login no Azure
      uses: Azure/login@v1.1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Swap Slots Dev to Prod
      uses: Azure/cli@1.0.4
      with:
        # Specify the script here
        inlineScript: az webapp deployment slot swap -n ${{ env.NOME_WEBAPP_AZURE }} -g "github-actions" -s "preprod" --target-slot "production"

